In [3]:
import numpy as np

# Creating Numpy Arrays


In [11]:
# np.array

a = np.array([1,2,3,4,5])    # vector
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


#

In [12]:
# 2D and 3D

b = np.array([[1,2,3,4],[5,4,3,2]])  # Metrix
b

array([[1, 2, 3, 4],
       [5, 4, 3, 2]])

In [15]:
b = np.array([[[1,2],[4,5]],[[7,9],[4,3]]])  # Tensor
b

array([[[1, 2],
        [4, 5]],

       [[7, 9],
        [4, 3]]])

#

In [16]:
# dtype

np.array([1,2,3,4],dtype = 'f')

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([1,2,3,4],dtype = bool)

array([ True,  True,  True,  True])

In [18]:
np.array([1,2,3,4],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

#

In [19]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [25]:
# with reshape

np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#

In [29]:
# np.ones and np.zeros

np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.ones((3,4),np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [31]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#

In [32]:
# np.random
np.random.random((4,5))

array([[0.492659  , 0.55449932, 0.76764621, 0.76095208, 0.41398253],
       [0.32444825, 0.2655566 , 0.58519628, 0.16215505, 0.05283632],
       [0.97838652, 0.17120991, 0.47886115, 0.50137062, 0.14319607],
       [0.75024706, 0.05646794, 0.02622498, 0.61266812, 0.51032955]])

#

In [35]:
# np.linspace  ( linear space)  # generate value between two point in equal divided

np.linspace(1,10,5)   # starting , ending , number of values 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#

In [39]:
# np.identity

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])