# Array Attributes

In [1]:
import numpy as np

In [20]:
a1 = np.arange(10,dtype = np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [21]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [22]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#

In [23]:
# ndim ( number od dimention)

a1.ndim

1

In [24]:
a2.ndim

2

In [25]:
a3.ndim

3

#

In [26]:
# shape

a1.shape

(10,)

In [27]:
a2.shape

(3, 4)

In [28]:
a3.shape

(2, 2, 2)

#

In [29]:
# size ( number of item)

a1.size

10

In [30]:
a2.size

12

In [31]:
a3.size

8

#

In [36]:
# itemsize  ( about item in memery)
a1.itemsize

4

In [37]:
a2.itemsize

8

In [38]:
a3.itemsize

8

#

In [39]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64
