In [1]:
import numpy as np

In [2]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# scalar operations

In [7]:
# Arithmetic

print(a1 *2)
print()
print(a1-4)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]

[[-4 -3 -2 -1]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [9]:
# Relational operation

a2 > 17

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

# vector operations

In [12]:
# Arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])