In [1]:
import  numpy as np

# Functions

In [2]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a2


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
# max / min/sum/ prod

np.max(a2)

np.int64(23)

In [13]:
np.max(a2,axis=0)  # 0 for colomn
                   # 1 for row 

array([20, 21, 22, 23])

In [6]:
np.min(a2)

np.int64(12)

In [11]:
np.min(a2,axis=1)

array([12, 16, 20])

In [7]:
np.sum(a1)

np.int64(66)

In [10]:
np.prod(a2)

np.int64(647647525324800)

#

In [14]:
# mean/madian/std/var

np.mean(a1)

np.float64(5.5)

In [15]:
np.mean(a2,axis=1)

array([13.5, 17.5, 21.5])

In [16]:
np.median(a2)

np.float64(17.5)

In [17]:
np.std(a1)

np.float64(3.452052529534663)

In [18]:
np.var(a2)

np.float64(11.916666666666666)

#

In [19]:
# Trigonometric function

np.sin(a1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

# 

In [20]:
# Dot product
# a1 row = a2 colomn
# a1 colomn = a2 row

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)

a1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

#

In [25]:
# log and exponents

np.log(a2)  # if array in 0 then numpy give C:\Users\rakes\AppData\Local\Temp\ipykernel_20228\174362789.py:3: RuntimeWarning: divide by zero encountered in log




array([[2.48490665, 2.56494936, 2.63905733],
       [2.7080502 , 2.77258872, 2.83321334],
       [2.89037176, 2.94443898, 2.99573227],
       [3.04452244, 3.09104245, 3.13549422]])

In [26]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

#

In [28]:
# round/floor/ceil

a = np.random.random((2,3)) *100
a

array([[82.51733028, 50.8894611 , 86.23741851],
       [57.43796549, 60.53383959,  2.88691177]])

In [29]:
np.round(a)

array([[83., 51., 86.],
       [57., 61.,  3.]])

In [30]:
np.floor(a)

array([[82., 50., 86.],
       [57., 60.,  2.]])

In [31]:
np.ceil(a)

array([[83., 51., 87.],
       [58., 61.,  3.]])