In [1]:
import numpy as np


# Indexing and Slicing

In [2]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [3]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a1[-1]

np.int64(9)

In [6]:
a2[1,1]

np.int64(5)

In [9]:
a2[2,3]

np.int64(11)

In [10]:
 a3[0,1,0]

np.int64(2)

In [11]:
a3[1,1,1]

np.int64(7)

#

In [12]:
# slicing

In [13]:
a1[1:7]

array([1, 2, 3, 4, 5, 6])

In [15]:
a1[0:9:2]

array([0, 2, 4, 6, 8])

In [16]:
a2[0,:]

array([0, 1, 2, 3])

In [17]:
a2[:,2]

array([ 2,  6, 10])

In [21]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [23]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [25]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [26]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [27]:
a3[:1,1:,:]

array([[[2, 3]]])

In [29]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [31]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [32]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [34]:
a3[0,1:2]

array([[3, 4, 5]])

In [35]:
a3[1,:,1]

array([10, 13, 16])

In [36]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [37]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])