In [1]:
import numpy as np

# Iteration

In [3]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [8]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [10]:
# 3D items print in seperate

In [11]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


# Reshaping

In [12]:
# reshape

In [13]:
# Transpose
np.transpose(a1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
# ravel

a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])